---

- name: Create venv for Shodan
  command: python3 -m venv /opt/osint-tools/shodan-env/
  args:
    creates: /opt/osint-tools/shodan-env
  tags: shodan

- name: Install shodan in vevnv
  pip:
    name: shodan
    virtualenv: /opt/osint-tools/shodan-env
  tags: shodan

- name: Symlink shodan binary to /usr/local/bin
  file:
    src: /opt/osint-tools/shodan-env/bin/shodan
    dest: /usr/local/bin/shodan
    state: link
  tags: shodan
