---

- name: create GoPhish destination directory
  file:
    path: /opt/osint-tools/gophish
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: gophish

- name: download GoPhish
  get_url:
    url: "https://github.com/gophish/gophish/releases/download/v0.12.1/gophish-v0.12.1-linux-64bit.zip"
    dest: /tmp/gophish.zip
  tags: gophish

- name: Unzip GoPhish
  unarchive:
    src: /tmp/gophish.zip
    dest: /opt/osint-tools/gophish/
    remote_src: yes
  tags: gophish

- name: Make GoPhish binary executable
  file:
    path: /opt/osint-tools/gophish/gophish
    mode: '0755'
  tags: gophish

- name: Backup default config file
  copy:
    src: /opt/osint-tools/gophish/config.json
    dest: /opt/osint-tools/gophish/config.json.bak
    remote_src: yes
  tags: gophish

- name: Create Systemd service
  copy:
    dest: /etc/systemd/system/gophish.service
    content: |
      [Unit]
      Description=GoPhish Service
      After=network.target

      [Service]
      WorkingDirectory=/opt/osint-tools/gophish
      ExecStart=/opt/osint-tools/gophish/gophish
      Restart=always

      [Install]
      WantedBy=multi-user.target
  tags: gophish

- name: Reload systemd to read new service
  systemd:
    daemon_reload: yes
  tags: gophish

- name: Enable GoPhish service
  systemd:
    name: gophish
    enabled: yes
    state: started      
  tags: gophish
