---
- name: OSINT tools
  hosts: ec2
  become: true
  vars:
    install_path: /opt/osint-tools

  roles:
    - role: amass
    - role: base
    - role: bbot
    - role: evilginx
    - role: gitdorker
    - role: gophish
    - role: shodan
    - role: subfinder
    - role: trufflehog
    - role: theharvester
