- name: Clone theHarvester repo
  git:
    repo: https://github.com/laramies/theHarvester.git
    dest: "{{ install_path }}/theHarvester"
    version: master
  tags: theharvester

- name: Create venv for theHarvester
  command: python3 -m venv {{ install_path }}/theHarvester/venv
  args:
    creates: "{{ install_path }}/theHarvester/venv"
  tags: theharvester

- name: Install theHarvester dependencies in venv
  pip:
    requirements: "{{ install_path }}/theHarvester/requirements.txt"
    virtualenv: "{{ install_path }}/theHarvester/venv"
  tags: theharvester

- name: Create wrapper script for theHarvester
  copy:
    dest: /usr/local/bin/theharvester
    mode: '0755'
    content: |
      #!/bin/bash
      {{ install_path }}/theHarvester/venv/bin/python {{ install_path }}/theHarvester/theHarvester.py "$@"
  tags: theharvester
