---
- name: Clone GitDorker repo
  git:
    repo: https://github.com/obheda12/GitDorker.git
    dest: "{{ install_path }}/GitDorker"
  tags: gitdorker

- name: Install GitDorker requirements
  pip:
    requirements: "{{ install_path }}/GitDorker/requirements.txt"
  tags: gitdorker

- name: Create symlink for GitDorker
  file:
    src: "{{ install_path }}/GitDorker/GitDorker.py"
    dest: /usr/local/bin/gitdorker
    state: link
  tags: gitdorker
