---
- name: Clone GitDorker repo
  git:
    repo: https://github.com/obheda12/GitDorker.git
    dest: "{{ install_path }}/GitDorker"
  tags: gitdorker

- name: Create venv for GitDorker
  command: python3 -m venv /opt/osint-tools/GitDorker/venv
  args:
    creates: /opt/osint-tools/GitDorker/venv
  tags: gitdorker

- name: Install requirements in venv
  pip:
    requirements: /opt/osint-tools/GitDorker/requirements.txt
    virtualenv: /opt/osint-tools/GitDorker/venv
  tags: gitdorker

- name: Create symlink for GitDorker
  file:
    src: "{{ install_path }}/GitDorker/GitDorker.py"
    dest: /usr/local/bin/gitdorker
    state: link
  tags: gitdorker
