---
- name: Check if required packages are installed
  apt:
    name:
      - git
      - python3-pip
      - unzip
      - snapd
      - pipx
      - make
      - golang
    state: present
    update_cache: true
  tags: base
